run:
  go: "1.21"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  uniq-by-line: false
linters:
  enable:
    - forbidigo
    - gofumpt
    - goimports
    - unparam

linters-settings:
  forbidigo:
    exclude-godoc-examples: true
    forbid:
      - "os.Exit"
      - "cobra.CheckErr"
  gofumpt:
    extra-rules: true
  goimports:
    # keep in sync with magefile
    local-prefixes: github.com/6RiverSystems,go.6river.tech
